spring.datasource:
  url: jdbc:mysql://localhost:3306/equityFeedsProcessing
  username: root
  password: root

spring.jpa:
  show-sql: true
  format_sql: true
  use-sql-comments: true
  hibernate.ddl-auto: update
#  hibernate.naming-strategy: org.hibernate.cfg.SpringPhysicalNamingStrategy
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring:
  activemq:
  in-memory: false
  pool.enabled: false
  jms:
      pub-sub-domain: true
  quartz:
      job-store-type: memory

activemq:
  broker-url: tcp://localhost:61616

server:
  port: 8082

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE

reuters:
  inboundTopicName: reuters.inbound.Topic
  outboundTopicName: reuters.outbound.topic

bloomberg:
  inboundTopicName: bloomberg.inbound.Topic
  outboundTopicName: bloomberg.outbound.Topic

capitalIQ:
  inboundTopicName: capitalIQ.inbound.Topic
  outboundTopicName: capitalIQ.outbound.Topic

nasdaq:
  outboundTopicName: nasdaq.outbound.Topic